# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "bytesto4t/src-tauri"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: chore(deps): update"

  - package-ecosystem: "cargo"
    directory: "external/hlbc"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: chore(deps): update"

  - package-ecosystem: "npm"
    directory: "bytesto4t"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: chore(deps): update"
