name: Build bytesto4t

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4

      - name: Checkout hlbc repository
        uses: actions/checkout@v4
        with:
          repository: FirowMD/hlbc
          path: external/hlbc
          ref: master

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: bytesto4t

      - name: Build hlbc
        run: cargo build --release
        working-directory: external/hlbc

      - name: Build Svelte app
        run: bun run tauri build
        working-directory: bytesto4t
    
      - name: Upload build artifact
        uses: softprops/action-gh-release@v2
        with:
          name: bytesto4t-artifacts
          files: |
            bytesto4t/src-tauri/target/release/bundle/msi/bytesto4t_0.1.2_x64_en-US.msi
            bytesto4t/src-tauri/target/release/bundle/nsis/bytesto4t_0.1.2_x64-setup.exe