name: Build bytesto4t

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "::add-path::${HOME}/.bun/bin"

      - name: Install dependencies
        run: bun install

      - name: Build Svelte app
        run: bun run build

      - name: Build Tauri app
        run: bun run tauri build

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "::add-path::${HOME}/.bun/bin"

      - name: Install dependencies
        run: bun install

      - name: Build Svelte app
        run: bun run build

      - name: Build Tauri app
        run: bun run tauri build